sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - python --version
  - uname -a
  - ls
install:
  - "python setup.py install"
  - "pip install coveralls"
  - "pip install pytest-runner"
  - "pip install pytest-cov"
script: "py.test --cov-config .coveragerc --cov=PyPWA"
after_success:
  - coveralls
notifications:
  email:
    on_success: change
    on_failure: change

