sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - python --version
  - uname -a
  - ls -a
  - "pip install coveralls"
  - "pip install coverage"
  - "pip install pytest"
  - "pip install pytest-runner"
install:
  - "pip install ."
script: "coverage run --source PyPWA -m py.test"
after_success:
  - ls -a
  - coveralls
  - cat .coverage
notifications:
  email:
    on_success: change
    on_failure: change

