sudo: required
dist: trusty
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
virtualenv:
  system_site_packages: true
matrix:
  allow_failures:
    - python: "3.6-dev"
addons:
  apt:
    packages:
      - "build-essential"
      - "gfortran"
      - "libatlas-base-dev"
before_install:
  - python --version
  - uname -a
  - ls -a
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --upgrade numpy scipy"
  - "pip install --upgrade iminuit nestle ruamel.yaml tabulate appdirs"
  - "pip install --upgrade fuzzywuzzy python-Levenshtein"
  - "pip install coveralls --upgrade"
  - "pip install coverage --upgrade"
  - "pip install pytest --upgrade"
  - "pip install pytest-runner --upgrade"
  - "pip install pytest-cov --upgrade"
  - "pip install pytest-logging --upgrade"
install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pyqt5
  - "pip install -e ."
script: "py.test --cov=PyPWA tests/ -vvvv"
after_success:
  - ls -a
  - coveralls
  - head .coverage
notifications:
  emails:
    on_success: change
    on_failure: change
