sudo: false
language: python
cache: pip
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - python --version
  - uname -a
  - ls -a
install:
  - "python setup.py install"
  - "pip install coveralls"
  - "pip install coverage"
  - "pip install pytest-runner"
  - "pip install pytest-cov"
script: "py.test --cov-config .coveragerc --cov=./PyPWA tests/"
after_success:
  - ls -a
  - coveralls
  - cat .coverage
notifications:
  email:
    on_success: change
    on_failure: change

