sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
  - python --version
  - uname -a
  - ls -a
  - "pip install coveralls --upgrade"
  - "pip install coverage --upgrade"
  - "pip install pytest --upgrade"
  - "pip install pytest-runner --upgrade"
  - "pip install pytest-cov --upgrade"
  - "pip install pytest-logging --upgrade"
install:
  - "pip install -e ."
script: "py.test --cov=PyPWA tests/ -vvvv"
after_success:
  - ls -a
  - coveralls
  - head .coverage
notifications:
  slack:
    rooms:
      - pypwa:qPFpdrleMXOkj6mE18RctZQR
    on_success: change
    on_failure: change
