sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
matrix:
  allow_failures:
    - python: "3.6-dev"
addons:
  apt:
    packages:
      - "build-essential"
      - "gfortran"
      - "libatlas-base-dev"
      - "python-pyqt5"
      - "python3-pyqt5"
before_install:
  - python --version
  - uname -a
  - ls -a
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --upgrade numpy scipy"
  - "pip install --upgrade iminuit nestle ruamel.yaml tabulate appdirs"
  - "pip install --upgrade fuzzywuzzy python-Levenshtein"
  - "pip install coveralls --upgrade"
  - "pip install coverage --upgrade"
  - "pip install pytest --upgrade"
  - "pip install pytest-runner --upgrade"
  - "pip install pytest-cov --upgrade"
  - "pip install pytest-logging --upgrade"
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - curl -L http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz -o /downloads/sip.tar.gz
  - curl -L https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.8.2/PyQt5_gpl-5.8.2.tar.gz -o /downloads/PyQt5_gpl-5.8.2.tar.gz
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds

install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get install -y libqt5-dev
    - sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev
    # Qt5
    - pushd /builds
    # SIP
    - tar xzf /downloads/sip.tar.gz --keep-newer-files
    - pushd sip-4.16.5
    - python configure.py
    - make
    - sudo make install
    - popd
    # PyQt5
    - tar xzf /downloads/PyQt5_gpl-5.8.2.tar.gz --keep-newer-files
    - pushd PyQt5_gpl-5.8.2.tar.gz
    - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui -e QtTest
    - make
    - sudo make install
    - popd
    # Builds Complete
    - popd
    - pip install -r requirements.txt
    - "pip install -e ."
script: "py.test --cov=PyPWA tests/ -vvvv"
after_success:
  - ls -a
  - coveralls
  - head .coverage
notifications:
  emails:
    on_success: change
    on_failure: change
